---
sudo: required
dist: trusty
language: generic

before_install:
  - sudo apt-get update -qq

install:
  # install ansible
  - sudo pip install ansible

  # configure ansible
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # check syntax
  - "ansible-playbook -i test/inventory test/test.yml --syntax-check"
